---
title: Kylie King's DSAN 6750 GIS project
authors:
  - name: Kylie King
    affiliation: Georgetown University
    roles: writing
    corresponding: true
bibliography: references.bib
---

## Abstract
The purpose of this project is to investigate whether Ireland is caring for its historic fairy habitats. Because fairies are notorious for obstructing data collection and interfering with computer calculations, there is very little data available on fairy habitats and their preservation. This is a two-part project, where we first determine where fairies prefer to live, and then assess whether their preferred habitat is flourishing. Data collected (with much sacrifice) on the location of fairy barrows (homes) will be converted into a density layer to determine where fairy barrows are most densely clustered. Next, land cover data from 1990 will be compared to the barrow density to determine which habitat fairies prefer. Finally,  land cover data from 2018 will be compared to the 1990 dataset, to produce a change matrix, and identify whether Irish fairy habitat remains intact.


## Literature Review
mostly talking about stories about fairies, for funsies

# Data Collection and Preparation
Barrows data, two land cover datas, natural earth data country layer

## Hypotheses
Hypothesis 1: Fairies mainly live in forested areas
Hypothesis 2: In accordance with global trends, fairy habitat is declining.

## Where Do Fairies Live?
probably forests I think

# Viewing Window Construction
probably all of ireland, but check for convex hulls

# Intensity Layer Construction
wahoooo 

# Land Cover Analysis
this is where I have to do interesting things with a raster, not sure how to do that yet. Will definitely have to reclassify to make sure the two land covers match

## Fairy Habitat Preservation
small little paragraph about what we have to do, also maybe prepping the land cover

# Change Matrix
no idea how do to this, wheeeeeeee

## Discussion and Findings
the irish people are probably in danger because i bet fairy habitat has declined